

#Server config
SERVER_HOST: "localhost"
SERVER_PORT: 8082

#ENV
ENV: "local"

# Arango config
ARANGO_SERVER: "http://localhost:8529/"
ARANGO_USER :  ""
ARANGO_PASSWORD :  ""
ARANGO_DB_AUTH: ""

#Log config
LOG_LEVEL: "DEBUG"

#Redis config
REDIS_SERVER: "localhost"
REDIS_PORT: 6379
REDIS_DB: "0"

#ElasticSearch config
ES_SERVER: "http://localhost:9200"

#Jaeger config
JAEGER_AGENT_HOST: 'localhost'
JAEGER_AGENT_PORT: '6831'
JAEGER_LOG_SPANS: false
JAEGER_SAMPLER_PARAM: "1"
JAEGER_SAMPLER_TYPE: "const"

#LogStash
LOGSTASH_HOST: ''
LOGSTASH_PORT: ''

#Pulsar Queue
PULSAR_QUEUE_HOST: ''
PULSAR_QUEUE_SUBSCRIPTION: ''
PULSAR_QUEUE_REQ_TOPIC: ''
PULSAR_QUEUE_RES_TOPIC: ''

#Static Token
STATIC_TOKEN: 'JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfZG9jIjp7InVzZXJJZCI6IjliODZjMGVlLTIxODUtNGNkMi05YjQ0LTQ3NWQ3MmRhMTkyNiIsImF0aGVuYUlkIjoiZDVjYzBkOTItNTk5YS00MDRkLTk2MzUtMGEyYjVlNzRlNGMwIiwiZW1haWwiOiJqYXlhbml2ZXRoYS5zZWx2YXJhakBjb252ZXJzaWdodC5haSIsImFwcElkIjoiTkEiLCJjbGllbnRJZCI6Ik5BIiwiZGlzcGxheU5hbWUiOiJKYXlhIE5pdmV0aGEiLCJyb2xlIjoidXNlciIsImFjY2Vzc0xpc3QiOlsidXNlciIsImRhdGFBZG1pbiIsIm9yZ0FkbWluIl0sIm9yZ0lkIjoiNjY0YTMwNzctZTY2Zi00ZDhkLWE0YzgtZjVhNTRiNjYyZmFmIiwiZGV2aWNlSWQiOiIxMjM0NTYiLCJkZXZpY2VOYW1lIjoiQnJvd3NlcldlYiIsImlzVHJpYWxVc2VyIjpmYWxzZX0sImlhdCI6MTYyOTUzNTgwM30.jo7SuElMYnn3ba808LNxf2pGS7X2S79IL9jfHrjkR8g'

#datasetIds
DATASET_ID: []

#Endpoints
AGENT_ENGINE: "http://localhost:8088"

#Sentry config
SENTRY_DSN: ""

