
#Log config
LOG_LEVEL: "DEBUG"

#Static Token
STATIC_TOKEN: ""

#Endpoints
AGENT_ENGINE: "https://api.conversight.ai/agent"

#Database Details
mySQL:
  host: ""
  port: ""
  username: ""
  password: ""
  database: ""
  timeout: 5
